---
title: "Unit 4 - 6 Review Starter"
author: "Insert your group number and name here"
date: "Insert date here"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(lubridate)
library(janitor)
```

## Exercises

# Part I - Data Types and Classes

## Exercise 1 - Create some vectors

#### Member 1

Add your code here.

#### Member 2

Add your code here.

#### Member 3

Add your code here.

#### Member 4

Add your code here.

#### Member 5

Add your code here.

## Exercise 2 - Combine into a data frame and pull the vectors

#### Member 1

Add your code here.

#### Member 2

Add your code here.

#### Member 3

Add your code here.

#### Member 4

Add your code here.

#### Member 5

Add your code here.

## Exercise 3 - Remove an element from each vector, except one

#### Member 1

Add your code here.

#### Member 2

Add your code here.

#### Member 3

Add your code here.

#### Member 4

Add your code here.

#### Member 5

Add your code here.

## Exercise 4 - Try to recombine as a data frame, instead use list

#### Member 1

Add your code here.

#### Member 2

Add your code here.

#### Member 3

Add your code here.

#### Member 4

Add your code here.

#### Member 5

Add your code here.

## Part II - Importing and Recoding Data

## Exercise 5

#### Member 1

Add your code here.

#### Member 2

Add your code here.

#### Member 3

Add your code here.

#### Member 4

Add your code here.

#### Member 5

Add your code here.

## Exercise 6

#### Member 1

Add your code here.

#### Member 2

Add your code here.

#### Member 3

Add your code here.

#### Member 4

Add your code here.

#### Member 5

Add your code here.
